# Generated by Django 2.0.7 on 2018-09-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cover', models.ImageField(upload_to='bazaar/')),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(upload_to='bazaar/')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='ClothType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'ClothType',
                'verbose_name_plural': 'ClothTypes',
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('cover', models.ImageField(upload_to='bazaar/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='wholesale.Book')),
                ('clothType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.ClothType')),
            ],
            options={
                'verbose_name': 'Piece',
                'verbose_name_plural': 'Pieces',
            },
        ),
        migrations.CreateModel(
            name='PieceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bazaar/')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wholesale.Piece')),
            ],
            options={
                'verbose_name': 'PieceImage',
                'verbose_name_plural': 'PieceImages',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='brand',
            field=models.ManyToManyField(to='wholesale.Brand'),
        ),
    ]
