# Generated by Django 2.2.5 on 2020-10-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0002_auto_20201017_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='dupattaType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dupatta', to='wholesale.ClothType'),
            preserve_default=False,
        ),
    ]
