# Generated by Django 2.2.5 on 2020-10-17 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_piece_dupattatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('businessName', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='NEW', max_length=100)),
                ('cartBooks', models.ManyToManyField(to='wholesale.Book')),
                ('contactInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='wholesale.ContactInfo')),
            ],
        ),
    ]
