# Generated by Django 2.2.5 on 2020-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_contactinfo_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pieceCount',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
