# Generated by Django 2.0.7 on 2018-09-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0001_initial'),
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scroller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.Book')),
            ],
        ),
    ]
